// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cllxygpsdlajczswfwgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsbHh5Z3BzZGxhamN6c3dmd2d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5Njg5NjAsImV4cCI6MjA3NDU0NDk2MH0.0BSU0QOW4mk6OdTiC3doODWAQfgZYqVckayd7_Cd68Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});